### ISSUE TITLE
tensorflow dataset and gpu

### ISSUE THREAD

**Issue by proto-n** [vlad17/vlad17.github.io#2]
Edit: Nevermind, I just realized that you do indeed use prefetch

Hi! Just some quick thoughts relating to https://vlad17.github.io/2017/12/23/beating-tf-api-in-vram.html

First, when fiddling around with datasets, be sure to try the .prefetch() function. It loads a few records/batches (depending on place of invocation) in advance, so that they are ready when processing needs to be done. For example in my example of

```
dataset = tf.data.Dataset.from_tensor_slices(data)\
    .repeat()\
    .shuffle(10*10**6)\
    .batch(batch_size)\
    .prefetch(2)\
    .filter(lambda x: tf.equal(tf.shape(x)[0], batch_size))
```
the prefetch line made processing an epoch more than 1.5x faster (about 3:20 to 2:05 minutes) when using an approach similar to your second one (with tf.while_loop).

Also, I think it is normal that your training is way faster when done entirely on the GPU. Usually though the training data doesn't fit in the GPU memory so you have too feed the GPU from regular RAM, and sometimes even read the data from files because it won't even fit in regular memory. These are the usecases when using the dataset API is convenient.

If you are doing little computation (and by that I mean not super-deep or super-large networks) then usually the bottleneck is not the GPU computing power, but the input pipeline (reading files, preprocessing on the CPU, transfering to GPU memory). This means that in this case you can increase the size/depth of the network without much effect on processing time.

Anyways that's my current understanding about this topic, but I'm still not completely confident when optimizing tensorflow, so take it with a grain of salt.

Also your article was helpful in gaining understanding, so thank you.

**Comment by vlad17** [comment]
Hey, just saw this! Thanks for dropping a note @proto-n and glad it was helpful :)
